// Generated by gencpp from file system_package/robot_1.msg
// DO NOT EDIT!


#ifndef SYSTEM_PACKAGE_MESSAGE_ROBOT_1_H
#define SYSTEM_PACKAGE_MESSAGE_ROBOT_1_H

#include <ros/service_traits.h>


#include <system_package/robot_1Request.h>
#include <system_package/robot_1Response.h>


namespace system_package
{

struct robot_1
{

typedef robot_1Request Request;
typedef robot_1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_1
} // namespace system_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::system_package::robot_1 > {
  static const char* value()
  {
    return "a78760cc430dc3134f2177ea1154f152";
  }

  static const char* value(const ::system_package::robot_1&) { return value(); }
};

template<>
struct DataType< ::system_package::robot_1 > {
  static const char* value()
  {
    return "system_package/robot_1";
  }

  static const char* value(const ::system_package::robot_1&) { return value(); }
};


// service_traits::MD5Sum< ::system_package::robot_1Request> should match 
// service_traits::MD5Sum< ::system_package::robot_1 > 
template<>
struct MD5Sum< ::system_package::robot_1Request>
{
  static const char* value()
  {
    return MD5Sum< ::system_package::robot_1 >::value();
  }
  static const char* value(const ::system_package::robot_1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::system_package::robot_1Request> should match 
// service_traits::DataType< ::system_package::robot_1 > 
template<>
struct DataType< ::system_package::robot_1Request>
{
  static const char* value()
  {
    return DataType< ::system_package::robot_1 >::value();
  }
  static const char* value(const ::system_package::robot_1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::system_package::robot_1Response> should match 
// service_traits::MD5Sum< ::system_package::robot_1 > 
template<>
struct MD5Sum< ::system_package::robot_1Response>
{
  static const char* value()
  {
    return MD5Sum< ::system_package::robot_1 >::value();
  }
  static const char* value(const ::system_package::robot_1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::system_package::robot_1Response> should match 
// service_traits::DataType< ::system_package::robot_1 > 
template<>
struct DataType< ::system_package::robot_1Response>
{
  static const char* value()
  {
    return DataType< ::system_package::robot_1 >::value();
  }
  static const char* value(const ::system_package::robot_1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SYSTEM_PACKAGE_MESSAGE_ROBOT_1_H
