// Generated by gencpp from file system_package/robot_2.msg
// DO NOT EDIT!


#ifndef SYSTEM_PACKAGE_MESSAGE_ROBOT_2_H
#define SYSTEM_PACKAGE_MESSAGE_ROBOT_2_H

#include <ros/service_traits.h>


#include <system_package/robot_2Request.h>
#include <system_package/robot_2Response.h>


namespace system_package
{

struct robot_2
{

typedef robot_2Request Request;
typedef robot_2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_2
} // namespace system_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::system_package::robot_2 > {
  static const char* value()
  {
    return "a78760cc430dc3134f2177ea1154f152";
  }

  static const char* value(const ::system_package::robot_2&) { return value(); }
};

template<>
struct DataType< ::system_package::robot_2 > {
  static const char* value()
  {
    return "system_package/robot_2";
  }

  static const char* value(const ::system_package::robot_2&) { return value(); }
};


// service_traits::MD5Sum< ::system_package::robot_2Request> should match 
// service_traits::MD5Sum< ::system_package::robot_2 > 
template<>
struct MD5Sum< ::system_package::robot_2Request>
{
  static const char* value()
  {
    return MD5Sum< ::system_package::robot_2 >::value();
  }
  static const char* value(const ::system_package::robot_2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::system_package::robot_2Request> should match 
// service_traits::DataType< ::system_package::robot_2 > 
template<>
struct DataType< ::system_package::robot_2Request>
{
  static const char* value()
  {
    return DataType< ::system_package::robot_2 >::value();
  }
  static const char* value(const ::system_package::robot_2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::system_package::robot_2Response> should match 
// service_traits::MD5Sum< ::system_package::robot_2 > 
template<>
struct MD5Sum< ::system_package::robot_2Response>
{
  static const char* value()
  {
    return MD5Sum< ::system_package::robot_2 >::value();
  }
  static const char* value(const ::system_package::robot_2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::system_package::robot_2Response> should match 
// service_traits::DataType< ::system_package::robot_2 > 
template<>
struct DataType< ::system_package::robot_2Response>
{
  static const char* value()
  {
    return DataType< ::system_package::robot_2 >::value();
  }
  static const char* value(const ::system_package::robot_2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SYSTEM_PACKAGE_MESSAGE_ROBOT_2_H
