// Generated by gencpp from file system_package/robot_feedback.msg
// DO NOT EDIT!


#ifndef SYSTEM_PACKAGE_MESSAGE_ROBOT_FEEDBACK_H
#define SYSTEM_PACKAGE_MESSAGE_ROBOT_FEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace system_package
{
template <class ContainerAllocator>
struct robot_feedback_
{
  typedef robot_feedback_<ContainerAllocator> Type;

  robot_feedback_()
    : robot_id(0)
    , robot_state()  {
    }
  robot_feedback_(const ContainerAllocator& _alloc)
    : robot_id(0)
    , robot_state(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _robot_id_type;
  _robot_id_type robot_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_state_type;
  _robot_state_type robot_state;





  typedef boost::shared_ptr< ::system_package::robot_feedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_package::robot_feedback_<ContainerAllocator> const> ConstPtr;

}; // struct robot_feedback_

typedef ::system_package::robot_feedback_<std::allocator<void> > robot_feedback;

typedef boost::shared_ptr< ::system_package::robot_feedback > robot_feedbackPtr;
typedef boost::shared_ptr< ::system_package::robot_feedback const> robot_feedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_package::robot_feedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_package::robot_feedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace system_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'system_package': ['/home/ys/mini_multi_agent/src/system_package/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::system_package::robot_feedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_package::robot_feedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_package::robot_feedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_package::robot_feedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_package::robot_feedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_package::robot_feedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_package::robot_feedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b52bed208b6aaa52d30f0cbe649c3fa0";
  }

  static const char* value(const ::system_package::robot_feedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb52bed208b6aaa52ULL;
  static const uint64_t static_value2 = 0xd30f0cbe649c3fa0ULL;
};

template<class ContainerAllocator>
struct DataType< ::system_package::robot_feedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_package/robot_feedback";
  }

  static const char* value(const ::system_package::robot_feedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_package::robot_feedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 robot_id\n\
string robot_state\n\
";
  }

  static const char* value(const ::system_package::robot_feedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_package::robot_feedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
      stream.next(m.robot_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_feedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_package::robot_feedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_package::robot_feedback_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.robot_id);
    s << indent << "robot_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_PACKAGE_MESSAGE_ROBOT_FEEDBACK_H
