// Generated by gencpp from file system_package/robot_2Response.msg
// DO NOT EDIT!


#ifndef SYSTEM_PACKAGE_MESSAGE_ROBOT_2RESPONSE_H
#define SYSTEM_PACKAGE_MESSAGE_ROBOT_2RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace system_package
{
template <class ContainerAllocator>
struct robot_2Response_
{
  typedef robot_2Response_<ContainerAllocator> Type;

  robot_2Response_()
    : task_state()  {
    }
  robot_2Response_(const ContainerAllocator& _alloc)
    : task_state(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _task_state_type;
  _task_state_type task_state;





  typedef boost::shared_ptr< ::system_package::robot_2Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_package::robot_2Response_<ContainerAllocator> const> ConstPtr;

}; // struct robot_2Response_

typedef ::system_package::robot_2Response_<std::allocator<void> > robot_2Response;

typedef boost::shared_ptr< ::system_package::robot_2Response > robot_2ResponsePtr;
typedef boost::shared_ptr< ::system_package::robot_2Response const> robot_2ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_package::robot_2Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_package::robot_2Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace system_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'system_package': ['/home/ys/mini_multi_agent/src/system_package/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::system_package::robot_2Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_package::robot_2Response_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_package::robot_2Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_package::robot_2Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_package::robot_2Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_package::robot_2Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_package::robot_2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adf0f1fee599407543390220f159892a";
  }

  static const char* value(const ::system_package::robot_2Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xadf0f1fee5994075ULL;
  static const uint64_t static_value2 = 0x43390220f159892aULL;
};

template<class ContainerAllocator>
struct DataType< ::system_package::robot_2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_package/robot_2Response";
  }

  static const char* value(const ::system_package::robot_2Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_package::robot_2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string task_state\n\
\n\
";
  }

  static const char* value(const ::system_package::robot_2Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_package::robot_2Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_2Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_package::robot_2Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_package::robot_2Response_<ContainerAllocator>& v)
  {
    s << indent << "task_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.task_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_PACKAGE_MESSAGE_ROBOT_2RESPONSE_H
