// Generated by gencpp from file system_package/robot_1Request.msg
// DO NOT EDIT!


#ifndef SYSTEM_PACKAGE_MESSAGE_ROBOT_1REQUEST_H
#define SYSTEM_PACKAGE_MESSAGE_ROBOT_1REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace system_package
{
template <class ContainerAllocator>
struct robot_1Request_
{
  typedef robot_1Request_<ContainerAllocator> Type;

  robot_1Request_()
    : task_id(0)  {
    }
  robot_1Request_(const ContainerAllocator& _alloc)
    : task_id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _task_id_type;
  _task_id_type task_id;





  typedef boost::shared_ptr< ::system_package::robot_1Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_package::robot_1Request_<ContainerAllocator> const> ConstPtr;

}; // struct robot_1Request_

typedef ::system_package::robot_1Request_<std::allocator<void> > robot_1Request;

typedef boost::shared_ptr< ::system_package::robot_1Request > robot_1RequestPtr;
typedef boost::shared_ptr< ::system_package::robot_1Request const> robot_1RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_package::robot_1Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_package::robot_1Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace system_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'system_package': ['/home/ys/mini_multi_agent/src/system_package/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::system_package::robot_1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_package::robot_1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_package::robot_1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_package::robot_1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_package::robot_1Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_package::robot_1Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_package::robot_1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9740a70b18b29c0d20fc5d8dff911576";
  }

  static const char* value(const ::system_package::robot_1Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9740a70b18b29c0dULL;
  static const uint64_t static_value2 = 0x20fc5d8dff911576ULL;
};

template<class ContainerAllocator>
struct DataType< ::system_package::robot_1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_package/robot_1Request";
  }

  static const char* value(const ::system_package::robot_1Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_package::robot_1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 task_id\n\
";
  }

  static const char* value(const ::system_package::robot_1Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_package::robot_1Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_1Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_package::robot_1Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_package::robot_1Request_<ContainerAllocator>& v)
  {
    s << indent << "task_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.task_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_PACKAGE_MESSAGE_ROBOT_1REQUEST_H
